"""Add last_sync_time to User model

Revision ID: 0e4d084ea1d1
Revises: 79c5598c8d90
Create Date: 2025-08-02 05:11:10.122036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4d084ea1d1'
down_revision: Union[str, Sequence[str], None] = '79c5598c8d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_sync_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_sync_time')
    # ### end Alembic commands ###
