"""Add OAuth tokens to User model

Revision ID: 79c5598c8d90
Revises: 5016f33d896a
Create Date: 2025-08-02 04:45:15.589993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c5598c8d90'
down_revision: Union[str, Sequence[str], None] = '5016f33d896a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_expiry')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
