"""Add unsubscribe_link to Email model

Revision ID: c09f24aafd00
Revises: f6c5ef922a22
Create Date: 2025-08-02 05:59:45.485744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09f24aafd00'
down_revision: Union[str, Sequence[str], None] = 'f6c5ef922a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('unsubscribe_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'unsubscribe_link')
    # ### end Alembic commands ###
